name: Status Check de pruebas

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - develop
      - main

jobs:
  hello_world:
    name: status check de pruebas
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: echo "Hi Devops"
      - name: Say hello
        run: echo "hi"
